export const AUTHORIZE_SUCCESS = 'AUTHORIZE_SUCCESS';
export const AUTHORIZE_FAIL = 'AUTHORIZE_FAIL';
export const WHOAMI_SUCCESS = 'WHOAMI_SUCCESS';
export const WHOAMI_FAIL = 'WHOAMI_FAIL';
export const AUTHENTICATE_FAIL = 'AUTHENTICATE_FAIL';